routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');


// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


Route::get('/', 'HomeController@index')->name('home');
Route::resource('blog', 'BlogController', ['only' => 'index']);
Route::get('blog/{blog}', 'BlogController@showBySlug')->name('blog.showBySlug');


Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('dashboard', 'DashboardController', ['only' => 'index']);
    Route::resource('blogs', 'BlogController');
    Route::resource('tags', 'TagController', ['except' => 'show']);
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{
    use SoftDeletes;
    
    protected $fillable = ['name'];

    public function blogs()
    {
        return $this->belongsToMany(Blog::class);
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\TagRequest;
use App\Http\Controllers\Controller;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('admin.tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        $newTag = Tag::create($request->input());
        return redirect()
            ->route('tags.index')
            ->with('success', "Created Tag: \"{$newTag->name}\"!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('admin.tag.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagRequest $request, Tag $tag)
    {
        $tag->update($request->input());
        return redirect()
            ->route('tags.index')
            ->with('success', "Updated Tag: \"{$tag->name}\"!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        return redirect()
            ->route('tags.index')
            ->with('success', "Tag \"{$tag->name}\" has been deleted!");
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.auth')

@section('main')
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <ol class="breadcrumb">
              <li><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
              <li><a href="{{ route('tags.index') }}">Tags</a></li>
              <li class="active">Create</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <form action="{{ route('tags.store') }}" method="POST">
                {{ csrf_field() }}

                <div class="panel panel-primary">
                    <div class="panel-heading">Create Tag</div>
                    <div class="panel-body">

                        <div class="form-group {{ ($errors->has('name')) ? 'has-error' : '' }}">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            @if($errors->has('name'))
                                <p class="help-text text-danger">{{ $errors->first('name') }}
                            @endif
                        </div>

                        <button type="submit" class="btn btn-success">Save</button>

                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tag/edit.blade.php
@extends('layouts.auth')

@section('main')
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <ol class="breadcrumb">
              <li><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
              <li><a href="{{ route('tags.index') }}">Tags</a></li>
              <li class="active">Edit</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <form action="{{ route('tags.update', $tag->id) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}

                <div class="panel panel-primary">
                    <div class="panel-heading">Create Tag</div>
                    <div class="panel-body">

                        <div class="form-group {{ ($errors->has('name')) ? 'has-error' : '' }}">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" name="name" value="{{ $tag->name }}">
                            @if($errors->has('name'))
                                <p class="help-text text-danger">{{ $errors->first('name') }}
                            @endif
                        </div>

                        <button type="submit" class="btn btn-success">Save</button>

                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.auth')

@section('main')
<div class="container">

    @if (session('success'))
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-success" role="alert">
                    <p>{{ session('success') }}</p>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-sm-12">
            <ol class="breadcrumb">
              <li><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
              <li class="active">Tags</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            @if(count($tags) < 1)
                <div class="panel panel-primary">
                    <div class="panel-body text-center">
                        <h2>You ain't got no tags.</h2>
                        <a href="{{ route('tags.create') }}" class="btn btn-primary btn-lg">Create one</a>  
                    </div>
                </div>
            @else
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <a href={{ route('tags.create') }} class="btn btn-default btn-sm pull-right">Create Tag</a>
                        <h1>Tags</h1>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($tags as $tag)
                                    <tr>
                                        <td>{{ $tag->name }}</td>
                                        <td>
                                            <form action="{{ route('tags.destroy', $tag->id) }}" method="POST" class='delete-form'>
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <button type="submit" class="btn btn-sm btn-danger pull-right btn-delete">Delete</button>
                                            </form>
                                            <a href={{ route('tags.edit', $tag->id) }} class="btn btn-sm btn-warning pull-right">Edit</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content panel-danger">
      <div class="modal-header panel-heading">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>Soft delete this?</p>
      </div>
      <div class="modal-footer panel-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger fersure-delete">Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@endsection

@section('scripts')
@parent

<script>
    $(document).ready(function () {
        var form = '';

        $('.delete-form').on('submit', function (e) {
            e.preventDefault();
            form = $(this);
            $('#myModal').modal();
        });

        $('.fersure-delete').on('click', function (){
            form[0].submit();
        });
    });
</script>
@endsection