routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');


// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


Route::get('/', 'HomeController@index')->name('home');
Route::resource('blog', 'BlogController', ['only' => 'index']);
Route::get('blog/{blog}', 'BlogController@showBySlug')->name('blog.showBySlug');


Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('dashboard', 'DashboardController', ['only' => 'index']);
    Route::resource('blogs', 'BlogController');
    Route::resource('tags', 'TagController', ['except' => 'show']);
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $fillable = [
        'title',
        'slug',
        'snippet',
        'body',
        'published'
    ];

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

app/Http/Controllers/Admin/BlogController.php
<?php


namespace App\Http\Controllers\Admin;

use App\Tag;
use App\Blog;
use Illuminate\Http\Request;
use App\Services\BlogService;
use App\Http\Requests\BlogRequest;
use App\Http\Controllers\Controller;

class BlogController extends Controller
{
    /**
     * Inject the needed services.
     * @param BlogService $blogService
     */
    public function __construct(BlogService $blogService)
    {
        $this->blogService = $blogService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::all();
        return view('admin.blog.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        return view('admin.blog.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogRequest $request)
    {
        $blog = $this->blogService->create($request->input());

        return redirect()
            ->route('blogs.index')
            ->with('success', "Blog \"{$blog->title}\" created!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        $tags = Tag::all();
        foreach ($tags as $tag) {
            $tag->selected = $blog->tags->contains($tag->id);
        }

        return view('admin.blog.edit', compact('tags', 'blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogRequest $request, $id)
    {
        $blog = $this->blogService->update($id, $request->input());

        return redirect()
            ->route('blogs.index')
            ->with('success', "Blog \"{$blog->title}\" updated!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        $blog->delete();

        return redirect()
            ->route('blogs.index')
            ->with('success', "Blog \"{$blog->title}\" has been deleted!");
    }
}

app/Http/Controllers/Api/V1/BlogController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Blog;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return 'adfadsf';
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        //
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->has('tag')) {
            $tagName = $request->tag;
            $blogs = Blog::whereHas('tags', function($query) use ($tagName) {
                $query->whereName($tagName);
            })
            ->wherePublished(1)
            ->get();
        } else {
            $blogs = Blog::wherePublished(1)->get();
        }
        
        return view('blog.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showBySlug($slug)
    {
        $blog = Blog::where('slug', $slug)
            ->wherePublished(1)
            ->first();
            
        return is_null($blog) ? view('errors.404') : view('blog.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/blog/create.blade.php
@extends('layouts.auth')

@section('css')
    @parent

    <link rel="stylesheet" href="/css/redactor.css">
@endsection

@section('main')
<div class="container">

    <div class="row">
        <div class="col-sm-12">

            <ol class="breadcrumb">
              <li><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
              <li><a href="{{ route('blogs.index') }}">Blogs</a></li>
              <li class="active">Create</li>
            </ol>

           @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
    
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h1>Create Blog</h1>
                </div>
                <div class="panel-body">
                    <form action="{{ route('blogs.store') }}" method="POST">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" class="form-control" />
                        </div>

                        <div class="form-group">
                            <label for="body">Body</label>
                            <textarea name="body"></textarea>
                        </div>

                        <div class="form-group">
                            <label>Publish
                            <div class="radio">
                              <label>
                                <input type="radio" name="published" value="1">
                                Yes
                              </label>
                            </div>
                            <div class="radio">
                              <label>
                                <input type="radio" name="published" value="0" checked>
                                No
                              </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags">Tags</label>
                            <select name="tags[]" class="form-control" multiple >
                                @foreach($tags as $tag)
                                    <option value="{{$tag->id}}">{{$tag->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection


@section('scripts')
    @parent
    <script src="/js/redactor.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {
        $('textarea[name="body"]').redactor({
            minHeight:  300
        });
    });
    </script>
@endsection

resources/views/admin/blog/edit.blade.php
@extends('layouts.auth')

@section('css')
    @parent

    <link rel="stylesheet" href="/css/redactor.css">
@endsection

@section('main')
<div class="container">

    <div class="row">
        <div class="col-sm-12">

            <ol class="breadcrumb">
              <li><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
              <li><a href="{{ route('blogs.index') }}">Blogs</a></li>
              <li class="active">Create</li>
            </ol>

           @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
    
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h1>Create Blog</h1>
                </div>
                <div class="panel-body">
                    <form action="{{ route('blogs.update', $blog->id) }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" class="form-control" value="{{ $blog->title }}" />
                        </div>

                        <div class="form-group">
                            <label for="body">Body</label>
                            <textarea name="body">{{ $blog->body }}</textarea>
                        </div>

                        <div class="form-group">
                            <label>Publish
                            <div class="radio">
                              <label>
                                <input type="radio" name="published" value="1" {{ $blog->published ? 'checked' : '' }}>
                                Yes
                              </label>
                            </div>
                            <div class="radio">
                              <label>
                                <input type="radio" name="published" value="0" {{ $blog->published ? '' : 'checked' }}>
                                No
                              </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags">Tags</label>
                            <select name="tags[]" class="form-control" multiple >
                                @foreach($tags as $tag)
                                    <option value="{{$tag->id}}" {{$tag->selected ? 'selected' : ''}}>{{$tag->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection


@section('scripts')
    @parent
    <script src="/js/redactor.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {
        $('textarea[name="body"]').redactor({
            minHeight:  300
        });
    });
    </script>
@endsection

resources/views/admin/blog/index.blade.php
@extends('layouts.auth')

@section('main')
<div class="container">

    @if (session('success'))
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-success" role="alert">
                    <p>{{ session('success') }}</p>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-sm-12">
            <ol class="breadcrumb">
              <li><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
              <li class="active">Blogs</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            @if(count($blogs) < 1)
                <div class="panel panel-primary">
                    <div class="panel-body text-center">
                        <h2>You ain't got no Blogs.</h2>
                        <a href="{{ route('blogs.create') }}" class="btn btn-primary btn-lg">Create one</a>  
                    </div>
                </div>
            @else
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <a href={{ route('blogs.create') }} class="btn btn-default btn-sm pull-right">Create Blog</a>
                        <h1>Blogs</h1>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Published</th>
                                    <th>Created On</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($blogs as $blog)
                                <tr>
                                    <td>{{ $blog->title }}</td>
                                    <td>{{ $blog->published ? 'Yup' : 'Nope' }}</td>
                                    <td>{{ $blog->created_at }}</td>
                                    <td>
                                        <form action="{{ route('blogs.destroy', $blog->id) }}" method="POST" class='delete-form'>
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-danger pull-right btn-delete">Delete</button>
                                        </form>
                                        <a href="{{ route('blogs.edit', $blog->id) }}" class="btn btn-warning pull-right">Edit</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            @endif
        </div>
    </div>
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content panel-danger">
      <div class="modal-header panel-heading">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>Soft delete this?</p>
      </div>
      <div class="modal-footer panel-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger fersure-delete">Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@endsection

@section('scripts')
@parent

<script>
    $(document).ready(function () {
        var form = '';

        $('.delete-form').on('submit', function (e) {
            e.preventDefault();
            form = $(this);
            $('#myModal').modal();
        });

        $('.fersure-delete').on('click', function (){
            form[0].submit();
        });
    });
</script>
@endsection